blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ è®¨è®ºåŒº
    url: https://github.com/Gardene-el/Coze2JianYing/discussions
    about: å¦‚æœ‰ä¸€èˆ¬æ€§é—®é¢˜æˆ–æƒ³è¦è®¨è®ºé¡¹ç›®ï¼Œè¯·è®¿é—®è®¨è®ºåŒº
